--- Copyright © 2026, YourLocalCappy, all rights deserved ---

--[[

ACT LIBRARY FOR HL2SBR BY YourLocalCappy!!!

]]
ACT = ACT or {}
PLAYER_ANIM = PLAYER_ANIM or {}
PLAYERANIMEVENT = PLAYERANIMEVENT or {}

PLAYER_ANIM.IDLE        = 0
PLAYER_ANIM.WALK        = 1
PLAYER_ANIM.RUN         = 2
PLAYER_ANIM.JUMP        = 3
PLAYER_ANIM.SWIM        = 4
PLAYER_ANIM.CROUCH      = 5
PLAYER_ANIM.CROUCHWALK  = 6
PLAYER_ANIM.ATTACK      = 7
PLAYER_ANIM.RELOAD      = 8
PLAYER_ANIM.DIE         = 9
PLAYER_ANIM.FLINCH      = 10
PLAYER_ANIM.MELEE       = 11
PLAYER_ANIM.THROW       = 12

PLAYERANIMEVENT.FIRE_GUN_PRIMARY   = 0
PLAYERANIMEVENT.FIRE_GUN_SECONDARY = 1
PLAYERANIMEVENT.RELOAD             = 2
PLAYERANIMEVENT.JUMP               = 3
PLAYERANIMEVENT.MELEE              = 4
PLAYERANIMEVENT.THROW_GRENADE      = 5
PLAYERANIMEVENT.DIE                = 6
PLAYERANIMEVENT.FLINCH             = 7

ACT.VM_IDLE                 = 168
ACT.VM_DRAW                 = 171
ACT.VM_HOLSTER              = 172
ACT.VM_PRIMARYATTACK        = 180
ACT.VM_SECONDARYATTACK      = 181
ACT.VM_RELOAD               = 182
ACT.VM_DRYFIRE              = 186
ACT.VM_IDLE_TO_LOWERED      = 187
ACT.VM_LOWERED_TO_IDLE      = 188
ACT.VM_THROW                = 190
ACT.VM_HITCENTER            = 191
ACT.VM_HITKILL              = 192
ACT.VM_SWINGHARD            = 193
ACT.VM_SWINGMISS            = 194

ACT.MP_STAND_IDLE                = 1048
ACT.MP_CROUCH_IDLE               = 1049
ACT.MP_RUN                       = 1058
ACT.MP_WALK                      = 1057
ACT.MP_CROUCHWALK                = 1061
ACT.MP_JUMP                      = 1064
ACT.MP_SWIM                      = 1066
ACT.MP_ATTACK_STAND_PRIMARYFIRE  = 1073
ACT.MP_ATTACK_CROUCH_PRIMARYFIRE = 1077
ACT.MP_RELOAD_STAND              = 1090
ACT.MP_RELOAD_CROUCH             = 1093
ACT.MP_GESTURE_FLINCH            = 1089
ACT.MP_DIE                       = 1099

ACT.HL2MP_IDLE                    = 953
ACT.HL2MP_IDLE_CROUCH             = 954
ACT.HL2MP_RUN                     = 955
ACT.HL2MP_WALK                    = 956
ACT.HL2MP_JUMP                    = 957
ACT.HL2MP_SWIM                    = 958

ACT.HL2MP_IDLE_PISTOL             = 1001
ACT.HL2MP_RUN_PISTOL              = 1002
ACT.HL2MP_IDLE_CROUCH_PISTOL      = 1003
ACT.HL2MP_WALK_CROUCH_PISTOL      = 1004
ACT.HL2MP_GESTURE_RANGE_ATTACK_PISTOL = 1005
ACT.HL2MP_GESTURE_RELOAD_PISTOL   = 1006

ACT.HL2MP_IDLE_SMG1               = 1021
ACT.HL2MP_RUN_SMG1                = 1022
ACT.HL2MP_IDLE_CROUCH_SMG1        = 1023
ACT.HL2MP_WALK_CROUCH_SMG1        = 1024
ACT.HL2MP_GESTURE_RANGE_ATTACK_SMG1 = 1025
ACT.HL2MP_GESTURE_RELOAD_SMG1     = 1026

ACT.HL2MP_IDLE_AR2                = 1031
ACT.HL2MP_RUN_AR2                 = 1032
ACT.HL2MP_IDLE_CROUCH_AR2         = 1033
ACT.HL2MP_WALK_CROUCH_AR2         = 1034
ACT.HL2MP_GESTURE_RANGE_ATTACK_AR2 = 1035
ACT.HL2MP_GESTURE_RELOAD_AR2      = 1036

ACT.HL2MP_IDLE_SHOTGUN            = 1041
ACT.HL2MP_RUN_SHOTGUN             = 1042
ACT.HL2MP_IDLE_CROUCH_SHOTGUN     = 1043
ACT.HL2MP_WALK_CROUCH_SHOTGUN     = 1044
ACT.HL2MP_GESTURE_RANGE_ATTACK_SHOTGUN = 1045
ACT.HL2MP_GESTURE_RELOAD_SHOTGUN  = 1046

ACT.HL2MP_IDLE_FISTS              = 977
ACT.HL2MP_RUN_FISTS               = 978
ACT.HL2MP_IDLE_CROUCH_FISTS       = 979
ACT.HL2MP_WALK_CROUCH_FISTS       = 980
ACT.HL2MP_GESTURE_RANGE_ATTACK_FISTS = 981
ACT.HL2MP_GESTURE_RELOAD_FISTS    = 982
ACT.HL2MP_JUMP_FISTS              = 983

ACT.HL2MP_IDLE_PHYSGUN            = 1131
ACT.HL2MP_RUN_PHYSGUN             = 1132
ACT.HL2MP_IDLE_CROUCH_PHYSGUN     = 1133
ACT.HL2MP_WALK_CROUCH_PHYSGUN     = 1134

ACT.HL2MP_IDLE_TOOL               = 1141
ACT.HL2MP_RUN_TOOL                = 1142
ACT.HL2MP_IDLE_CROUCH_TOOL        = 1143
ACT.HL2MP_WALK_CROUCH_TOOL        = 1144
ACT.HL2MP_GESTURE_RANGE_ATTACK_TOOL = 1145